# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Delicious-Export
version:      1.1
version_from: lib/Net/Delicious/Export.pm
installdirs:  site
requires:
    MD5:                           0
    Test::More:                    0
    XML::SAX:                      0.12

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
